WITH Dates AS
(
SELECT CAST('2025-01-01' AS DATE) AS DateValue

UNION ALL

SELECT DATEADD(DAY,1,DateValue)
FROM Dates
WHERE DateValue<'2025-01-31'
)

SELECT * FROM Dates
OPTION (MAXRECURSION 31);